# Generated by Django 4.0.2 on 2022-03-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='addresss',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='mail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
