# Generated by Django 4.0.2 on 2022-02-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0002_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookplot',
            name='downpayment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
