# Generated by Django 4.0.2 on 2022-03-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0003_alter_customer_addresss'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookplot',
            name='addresss',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='bookplot',
            name='mail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='addresss',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='mail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
