# Generated by Django 4.0.2 on 2022-03-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0006_customer_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(max_length=25)),
                ('user_id', models.CharField(max_length=300)),
                ('plot_number', models.CharField(max_length=25)),
                ('Payable_amout', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_no', models.BigIntegerField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=10, null=True)),
                ('remarks', models.TextField()),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipt/')),
                ('joinig_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
