# Generated by Django 4.0.2 on 2022-03-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0008_bookplot_booking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookplot',
            name='remaining_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
