# Generated by Django 4.0.2 on 2022-03-06 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0012_installment_payment_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookplot',
            old_name='booking_amount',
            new_name='payment_amount',
        ),
    ]
