# Generated by Django 4.0.2 on 2022-03-06 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0014_alter_installment_payment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookplot',
            old_name='payment_amount',
            new_name='booking_amount',
        ),
    ]
