# Generated by Django 4.0.2 on 2022-03-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0016_rename_booking_amount_bookplot_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='funddetails',
            name='owner',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
