# Generated by Django 4.0.2 on 2022-03-07 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0018_funddetails_joinig_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='addplot',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addplot',
            name='user_id',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
