# Generated by Django 4.0.2 on 2022-03-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0020_remove_addplot_owner_remove_addplot_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addplot',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='addplot',
            name='plc',
        ),
        migrations.RemoveField(
            model_name='addplot',
            name='plc_rate',
        ),
        migrations.RemoveField(
            model_name='bookplot',
            name='Mnthly_Installment',
        ),
        migrations.RemoveField(
            model_name='bookplot',
            name='number_of_Installment',
        ),
        migrations.AddField(
            model_name='funddetails',
            name='plot_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
