# Generated by Django 4.0.2 on 2022-03-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0021_remove_addplot_discount_remove_addplot_plc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funddetails',
            name='Total_amount',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
