# Generated by Django 4.0.2 on 2022-03-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0022_funddetails_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='funddetails',
            name='Payable_amout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funddetails',
            name='payment_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookplot',
            name='joinig_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='funddetails',
            name='joinig_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='joinig_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
